local FTN47 = "ftn47.slug"
local FTN57 = "ftn57.slug"
local FTN87 = "ftn87.slug"
local UNI47 = "univers47.slug"
local UNI55 = "univers55.slug"
local UNI57 = "univers57.slug"
local ANTIQUE = "proseantiquepsmt.slug"
EsoKR.fontFaces = {
    FTN47 = FTN47,
    FTN57 = FTN57,
    FTN87 = FTN87,
    UNI47 = UNI47,
    UNI55 = UNI55,
    UNI57 = UNI57,
    ANTIQUE = ANTIQUE,
    fonts = {
        ["Univers 47"] = UNI47,
        ["Univers 55"] = UNI55,
        ["Univers 57"] = UNI57,
        ["ProseAntique"] = ANTIQUE,
        ["Futura Condensed Book"] = FTN47,
        ["Futura Condensed Medium"] = FTN57,
        ["Futura Condensed Bold"] = FTN87,
    },
    ZO_TOOLTIP_STYLES = {
        abilityHeaderSection = FTN47,
        attributeBody = FTN47,
        -- attributeTitleSection = FTN87, -- 20210317 제거
        bagCountSection = FTN47,
        bodyHeader = FTN47,
        bodySection = FTN47,
        cadwellObjectiveTitle = FTN87,
        collectionsInfoSection = FTN47,
        companionOverviewDescription = FTN47, -- 20210620 추가
        currencyLocationTitle = FTN87,
        currencyStatValuePairStat = FTN47,
        currencyStatValuePairValue = FTN47,
        defaultAccessBody = FTN47,
        defaultAccessTopSection = FTN47,
        delveSkyshardHint = FTN47, -- 20220614
        delveSkyshardStatus = FTN47, -- 20220614
        giftName = FTN47, -- 20220614
        groupDescription = FTN47,
        instantUnlockIneligibilitySection = FTN47,
        itemComparisonStatValuePairValue = FTN47,
        itemTagsSection = FTN47,
        itemTradeBoPSection = FTN47,
        lootTooltip = FTN47,
        mapKeepUnderAttack = FTN87,
        mapLocationTooltipContentHeader = FTN47,
        mapLocationTooltipWayshrineHeader = FTN87,
        mapQuestTitle = FTN87,
        mapTitle = FTN87,
        quadrant_2_3_Tooltip = FTN47, -- 20210620 추가
        skillLineEntryHeader = FTN47, -- 20210620 추가
        skyshardHint = FTN47, -- 20220614
        socialTitle = FTN47,
        stableGamepadTooltip = FTN47,
        tooltip = FTN47,
        tributeBodyText = FTN47, -- 20220614
        tributeChooseOneText = FTN47, -- 20220614
        tributeDisabledMechanicText = FTN47, -- 20220614
        voiceChatBodyHeader = FTN47,
        worldMapTooltip = FTN47,
        -- 20210317 추가
        antiquityInfoSection = FTN47,
        dailyLoginRewardsLockedSection = FTN47,
        furnishingLimitTypeSection = FTN47,
        houseTemplateStatValuePairStat = FTN47,
        houseTemplateStatValuePairValue = FTN47,
        itemSetSeparatorSection = FTN47,
        redeemCodeBodySection = FTN47,
    },
    ZO_CRAFTING_TOOLTIP_STYLES = {
        abilityHeaderSection = FTN47,
        attributeBody = FTN47,
        -- attributeTitleSection = FTN87, -- 20210317 제거
        bagCountSection = FTN47,
        bodyHeader = FTN47,
        bodySection = FTN47,
        cadwellObjectiveTitle = FTN87,
        collectionsInfoSection = FTN47,
        companionOverviewDescription = FTN47, -- 20210620 추가
        currencyLocationTitle = FTN87,
        currencyStatValuePairStat = FTN47,
        currencyStatValuePairValue = FTN47,
        defaultAccessBody = FTN47,
        defaultAccessTopSection = FTN47,
        delveSkyshardHint = FTN47, -- 20220614
        delveSkyshardStatus = FTN47, -- 20220614
        giftName = FTN47, -- 20220614
        groupDescription = FTN47,
        instantUnlockIneligibilitySection = FTN47,
        itemComparisonStatValuePairValue = FTN47,
        itemTagsSection = FTN47,
        itemTradeBoPSection = FTN47,
        lootTooltip = FTN47,
        mapKeepUnderAttack = FTN87,
        mapLocationTooltipContentHeader = FTN47,
        mapLocationTooltipWayshrineHeader = FTN87,
        mapQuestTitle = FTN87,
        mapTitle = FTN87,
        quadrant_2_3_Tooltip = FTN47, -- 20210620 추가
        skillLineEntryHeader = FTN47, -- 20210620 추가
        skyshardHint = FTN47, -- 20220614
        socialTitle = FTN47,
        stableGamepadTooltip = FTN47,
        tooltip = FTN47,
        voiceChatBodyHeader = FTN47,
        worldMapTooltip = FTN47,
        -- 20210317 추가
        antiquityInfoSection = FTN47,
        dailyLoginRewardsLockedSection = FTN47,
        furnishingLimitTypeSection = FTN47,
        houseTemplateStatValuePairStat = FTN47,
        houseTemplateStatValuePairValue = FTN47,
        itemSetSeparatorSection = FTN47,
        redeemCodeBodySection = FTN47,
        tributeBodyText = FTN47, -- 20220614
        tributeChooseOneText = FTN47, -- 20220614
        tributeDisabledMechanicText = FTN47, -- 20220614
    },
    ZO_GAMEPAD_DYEING_TOOLTIP_STYLES = {
        body = FTN47,
        title = FTN47,
        tooltip = FTN47,
    },
}